project:
  type: book
  output-dir: "docs"
book:
  title: "Getting Started with OpenAI API: A Beginner's Guide"
  editor:
    markdown:
      wrap: 72
  author: "Animesh Devarshi"
  date: "11/04/2023"
  chapters:
    - index.qmd
    - 1_Chapter.qmd
    - 2_chapter.qmd
    - 3_Chapter.qmd
    - 4_Chapter.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    code-overflow: wrap
  pdf:
    documentclass: scrreprt

editor: visual

